version: 0.2

env:
  parameter-store:
    GITHUB_PERSONAL_ACCESS_TOKEN: GitHub-Personal-Access-Token

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
      - echo "<servers><server><id>github</id><username>iansteph</username><password>$GITHUB_PERSONAL_ACCESS_TOKEN</password></server></servers>" >> ./settings.xml # See here: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
      - echo "</settings>" >> ./settings.xml # Append closing XML tag to settings.xml Maven file to format file correctly
      - cp ./settings.xml /root/.m2/settings.xml
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - cd DeschedulerFunction
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo Build started on `date`
      - mvn package shade:shade
      - mv target/Descheduler-1.0.jar .
      - unzip Descheduler-1.0.jar
      - rm -rf target tst src buildspec.yaml pom.xml Descheduler-1.0.jar
      - aws cloudformation package --template ../template.yaml --s3-bucket nhlp3-descheduler-cloudformation-artifacts --output-template ../template-export.yaml

artifacts:
  files:
    - template-export.yaml