AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Descheduler

Resources:
  DeschedulerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: DeschedulerFunction
      Handler: iansteph.nhlp3.descheduler.handler.DeschedulerHandler::handleRequest
      Runtime: java8
      Description: Descheduler function for NHLP3 to set play-by-play-processing for games
      MemorySize: 512