AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Descheduler

Resources:
  DeschedulerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: DeschedulerFunction
      Handler: iansteph.nhlp3.descheduler.handler.DeschedulerHandler::handleRequest
      Runtime: java8
      Description: Descheduler function for NHLP3 to set play-by-play-processing for games
      MemorySize: 512
      Role:
        Fn::GetAtt:
          - DeschedulerFunctionExecutionRole
          - Arn
      Timeout: 60

  DeschedulerFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: NHLP3-Descheduler-Execution-Role
      Description: IAM Role assumed when invoking the Descheduler lambda function
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DeschedulerFunctionPolicyDocument
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - events:RemoveTargets
                  - events:DeleteRule
                Resource: '*'

  NHLP3PlayByPlayGameFinalEventSnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: arn:aws:sns:us-east-1:627812672245:NHLP3-Play-by-Play-Events-prod
      Protocol: lambda
      Endpoint:
        Fn::GetAtt:
          - DeschedulerFunction
          - Arn
      FilterPolicy:
        eventTypeId:
          - GAME_OFFICIAL

  EventPublisherSnsTopicTriggerLambaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
          - DeschedulerFunction
          - Arn
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: arn:aws:sns:us-east-1:627812672245:NHLP3-Play-by-Play-Events-prod